// <auto-generated />
using System;
using Capstone_RJTech.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capstone_RJTech.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827131740_AddCustomerAddress")]
    partial class AddCustomerAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Capstone_RJTech.Models.AppNotification", b =>
                {
                    b.Property<int>("notification_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notification_ID"));

                    b.Property<string>("action_url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("notification_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("product_ID")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("notification_ID");

                    b.HasIndex("product_ID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Checkout", b =>
                {
                    b.Property<int>("CheckoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckoutID"));

                    b.Property<int>("CheckoutNumber")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePurchased")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CheckoutID");

                    b.HasIndex("CheckoutNumber")
                        .IsUnique();

                    b.HasIndex("CustomerID");

                    b.ToTable("tblCheckout");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.CheckoutItem", b =>
                {
                    b.Property<int>("CheckoutItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckoutItemID"));

                    b.Property<int>("CheckoutID")
                        .HasColumnType("int");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CheckoutItemID");

                    b.HasIndex("CheckoutID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SerialNo")
                        .IsUnique()
                        .HasFilter("[SerialNo] IS NOT NULL");

                    b.ToTable("tblCheckoutItem");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Customer", b =>
                {
                    b.Property<int>("customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_ID"));

                    b.Property<string>("customer_Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("customer_Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("customer_FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("customer_Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("customer_ID");

                    b.HasIndex("customer_Email")
                        .IsUnique();

                    b.ToTable("tblCustomer");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Delivery", b =>
                {
                    b.Property<int>("delivery_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("delivery_ID"));

                    b.Property<string>("batch_ID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("date_delivered")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_archived")
                        .HasColumnType("bit");

                    b.Property<string>("received_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("delivery_ID");

                    b.HasIndex("batch_ID")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.DeliveryDetails", b =>
                {
                    b.Property<int>("deldetails_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deldetails_ID"));

                    b.Property<int>("delivery_ID")
                        .HasColumnType("int");

                    b.Property<int>("new_quantity")
                        .HasColumnType("int");

                    b.Property<int>("previous_quantity")
                        .HasColumnType("int");

                    b.Property<int>("product_ID")
                        .HasColumnType("int");

                    b.Property<int>("product_quantity")
                        .HasColumnType("int");

                    b.HasKey("deldetails_ID");

                    b.HasIndex("delivery_ID");

                    b.HasIndex("product_ID");

                    b.ToTable("DeliveryDetails");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.DocumentSequence", b =>
                {
                    b.Property<string>("sequence_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("last_value")
                        .HasColumnType("int");

                    b.HasKey("sequence_name");

                    b.ToTable("DocumentSequences");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Product", b =>
                {
                    b.Property<int>("product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_ID"));

                    b.Property<decimal>("Product_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("category_ID")
                        .HasColumnType("int");

                    b.Property<string>("product_brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("product_description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("product_image_path")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("product_quantity")
                        .HasColumnType("int");

                    b.Property<string>("product_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("reorder_level")
                        .HasColumnType("int");

                    b.HasKey("product_ID");

                    b.HasIndex("category_ID", "product_name", "product_brand")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            product_ID = 1,
                            Product_price = 200.00m,
                            category_ID = 2,
                            product_brand = "A4 Tech",
                            product_description = "Optical Wired Mouse",
                            product_name = "Optical Wired Mouse",
                            product_quantity = 0,
                            product_status = "Unavailable",
                            reorder_level = 5
                        },
                        new
                        {
                            product_ID = 2,
                            Product_price = 1200.00m,
                            category_ID = 3,
                            product_brand = "Logitech",
                            product_description = "Mechanical Keyboard",
                            product_name = "Mechanical Keyboard",
                            product_quantity = 0,
                            product_status = "Unavailable",
                            reorder_level = 5
                        });
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductCategory", b =>
                {
                    b.Property<int>("category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("category_ID"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("category_ID");

                    b.HasIndex("category_name")
                        .IsUnique();

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            category_ID = 1,
                            category_name = "Monitors"
                        },
                        new
                        {
                            category_ID = 2,
                            category_name = "Mouses"
                        },
                        new
                        {
                            category_ID = 3,
                            category_name = "Keyboards"
                        },
                        new
                        {
                            category_ID = 4,
                            category_name = "Headsets"
                        });
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ScheduleEvent", b =>
                {
                    b.Property<int>("event_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("event_ID"));

                    b.Property<string>("color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("end_time")
                        .HasColumnType("time");

                    b.Property<DateTime>("event_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("start_time")
                        .HasColumnType("time");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("event_ID");

                    b.ToTable("ScheduleEvents");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.AppNotification", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("product_ID")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Checkout", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Customer", "Customer")
                        .WithMany("Checkouts")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.CheckoutItem", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Checkout", "Checkout")
                        .WithMany("CheckoutItems")
                        .HasForeignKey("CheckoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany("CheckoutItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.DeliveryDetails", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Delivery", "Delivery")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("delivery_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("product_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Product", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("category_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Checkout", b =>
                {
                    b.Navigation("CheckoutItems");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Customer", b =>
                {
                    b.Navigation("Checkouts");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Delivery", b =>
                {
                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Product", b =>
                {
                    b.Navigation("CheckoutItems");

                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
