// <auto-generated />
using System;
using Capstone_RJTech.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Capstone_RJTech.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919132549_SeedFiveDefaultCategories")]
    partial class SeedFiveDefaultCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Capstone_RJTech.Models.AppNotification", b =>
                {
                    b.Property<int>("notification_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notification_ID"));

                    b.Property<string>("action_url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_read")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("notification_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("product_ID")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("notification_ID");

                    b.HasIndex("product_ID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.AppUser", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.BestSellingProductReport", b =>
                {
                    b.Property<int>("BestSellingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BestSellingID"));

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantitySold")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BestSellingID");

                    b.HasIndex("Period")
                        .IsUnique();

                    b.HasIndex("ProductID");

                    b.ToTable("tblBestSellingProduct");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Checkout", b =>
                {
                    b.Property<int>("CheckoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckoutID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePurchased")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CheckoutID");

                    b.HasIndex("CustomerID");

                    b.ToTable("tblCheckout");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.CheckoutItem", b =>
                {
                    b.Property<int>("CheckoutItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckoutItemID"));

                    b.Property<int>("CheckoutID")
                        .HasColumnType("int");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CheckoutItemID");

                    b.HasIndex("CheckoutID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SerialNo")
                        .HasFilter("[SerialNo] IS NOT NULL");

                    b.ToTable("tblCheckoutItem");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Customer", b =>
                {
                    b.Property<int>("customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customer_ID"));

                    b.Property<string>("customer_Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("customer_Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("customer_FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("customer_Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("customer_ID");

                    b.HasIndex("customer_Email")
                        .IsUnique();

                    b.ToTable("tblCustomer");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.CustomerPurchaseHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<int>("CheckoutID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HistoryID");

                    b.HasIndex("CheckoutID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("PurchaseDate", "HistoryID");

                    b.ToTable("tblCustomerPurchaseHistory");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Delivery", b =>
                {
                    b.Property<int>("delivery_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("delivery_ID"));

                    b.Property<string>("batch_ID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("date_delivered")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_archived")
                        .HasColumnType("bit");

                    b.Property<string>("received_by")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("delivery_ID");

                    b.HasIndex("batch_ID")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.DeliveryDetails", b =>
                {
                    b.Property<int>("deldetails_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deldetails_ID"));

                    b.Property<int>("delivery_ID")
                        .HasColumnType("int");

                    b.Property<int>("new_quantity")
                        .HasColumnType("int");

                    b.Property<int>("previous_quantity")
                        .HasColumnType("int");

                    b.Property<int>("product_ID")
                        .HasColumnType("int");

                    b.Property<int>("product_quantity")
                        .HasColumnType("int");

                    b.HasKey("deldetails_ID");

                    b.HasIndex("delivery_ID");

                    b.HasIndex("product_ID");

                    b.ToTable("DeliveryDetails");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.DeliveryOverviewReport", b =>
                {
                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalDeliveries")
                        .HasColumnType("int");

                    b.Property<int>("TotalItemsDelivered")
                        .HasColumnType("int");

                    b.Property<int>("TotalProductsDelivered")
                        .HasColumnType("int");

                    b.HasKey("LastUpdated");

                    b.ToTable("tblDeliveryOverview");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.DeliverySummaryReport", b =>
                {
                    b.Property<int>("DeliveryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("int");

                    b.HasKey("DeliveryID");

                    b.ToTable("tblDeliverySummary");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Installment", b =>
                {
                    b.Property<int>("InstallmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstallmentID"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CheckoutID")
                        .HasColumnType("int");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MonthlyPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Months")
                        .HasColumnType("int");

                    b.Property<int>("MonthsPaid")
                        .HasColumnType("int");

                    b.Property<int>("MonthsRemaining")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InstallmentID");

                    b.HasIndex("CheckoutID")
                        .IsUnique();

                    b.ToTable("tblInstallment");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.InstallmentPayment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<int>("InstallmentID")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PaymentID");

                    b.HasIndex("InstallmentID");

                    b.ToTable("tblInstallmentPayment");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.InventoryOverviewReport", b =>
                {
                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableProducts")
                        .HasColumnType("int");

                    b.Property<int>("LowStockProducts")
                        .HasColumnType("int");

                    b.Property<int>("OutOfStockProducts")
                        .HasColumnType("int");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UnavailableProducts")
                        .HasColumnType("int");

                    b.HasKey("LastUpdated");

                    b.ToTable("tblInventoryOverview");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.LeastSellingProductReport", b =>
                {
                    b.Property<int>("LeastSellingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeastSellingID"));

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantitySold")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LeastSellingID");

                    b.HasIndex("Period")
                        .IsUnique();

                    b.HasIndex("ProductID");

                    b.ToTable("tblLeastSellingProduct");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.LeastStockedProductReport", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductID");

                    b.ToTable("tblLeastStockedProduct");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.MonthlySalesReport", b =>
                {
                    b.Property<int>("MonthlySalesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonthlySalesID"));

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("TotalItemsSold")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MonthlySalesID");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("tblMonthlySales");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.MostStockedProductReport", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductID");

                    b.ToTable("tblMostStockedProduct");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.PasswordResetCode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("tblPasswordResetCode");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Product", b =>
                {
                    b.Property<int>("product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_ID"));

                    b.Property<decimal>("Product_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("category_ID")
                        .HasColumnType("int");

                    b.Property<bool>("is_serialized")
                        .HasColumnType("bit");

                    b.Property<byte[]>("product_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("product_ImageContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("product_brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("product_description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("product_quantity")
                        .HasColumnType("int");

                    b.Property<string>("product_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("reorder_level")
                        .HasColumnType("int");

                    b.HasKey("product_ID");

                    b.HasIndex("category_ID", "product_name", "product_brand")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            product_ID = 1,
                            Product_price = 200.00m,
                            category_ID = 2,
                            is_serialized = false,
                            product_brand = "A4 Tech",
                            product_description = "Optical Wired Mouse",
                            product_name = "Optical Wired Mouse",
                            product_quantity = 0,
                            product_status = "Unavailable",
                            reorder_level = 5
                        },
                        new
                        {
                            product_ID = 2,
                            Product_price = 1200.00m,
                            category_ID = 3,
                            is_serialized = false,
                            product_brand = "Logitech",
                            product_description = "Mechanical Keyboard",
                            product_name = "Mechanical Keyboard",
                            product_quantity = 0,
                            product_status = "Unavailable",
                            reorder_level = 5
                        });
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductCategory", b =>
                {
                    b.Property<int>("category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("category_ID"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("category_ID");

                    b.HasIndex("category_name")
                        .IsUnique();

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            category_ID = 1,
                            category_name = "Monitors"
                        },
                        new
                        {
                            category_ID = 2,
                            category_name = "Mouses"
                        },
                        new
                        {
                            category_ID = 3,
                            category_name = "Keyboards"
                        },
                        new
                        {
                            category_ID = 4,
                            category_name = "Headsets"
                        },
                        new
                        {
                            category_ID = 5,
                            category_name = "Computer Accessories"
                        });
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductCategoryOverviewReport", b =>
                {
                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UnavailableQuantity")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.ToTable("tblProductCategoryOverview");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductDeliverySummaryReport", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalDeliveries")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuantityDelivered")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("tblProductDeliverySummary");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductStockSummaryReport", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ProductID");

                    b.ToTable("tblProductStockSummary");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.SalesByCategoryReport", b =>
                {
                    b.Property<int>("SalesCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesCategoryID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateGenerated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalQuantitySold")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SalesCategoryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("Period", "CategoryID")
                        .IsUnique();

                    b.ToTable("tblSalesByCategory");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.SalesOverviewReport", b =>
                {
                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlySales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TodaySales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalCustomers")
                        .HasColumnType("int");

                    b.Property<int>("TotalItemsSold")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("int");

                    b.Property<decimal>("WeeklySales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YearlySales")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LastUpdated");

                    b.ToTable("tblSalesOverview");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.TransactionReport", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CheckoutID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionID");

                    b.HasIndex("CheckoutID")
                        .IsUnique();

                    b.HasIndex("CustomerID");

                    b.ToTable("tblTransaction");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.WeeklySalesReport", b =>
                {
                    b.Property<int>("WeeklySalesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeeklySalesID"));

                    b.Property<int>("TotalItemsSold")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WeeklySalesID");

                    b.HasIndex("WeekStartDate")
                        .IsUnique();

                    b.ToTable("tblWeeklySales");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.YearlySalesReport", b =>
                {
                    b.Property<int>("YearlySalesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YearlySalesID"));

                    b.Property<int>("TotalItemsSold")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTransactions")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("YearlySalesID");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("tblYearlySales");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.AppNotification", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("product_ID")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Capstone_RJTech.Models.BestSellingProductReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Checkout", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Customer", "Customer")
                        .WithMany("Checkouts")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.CheckoutItem", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Checkout", "Checkout")
                        .WithMany("CheckoutItems")
                        .HasForeignKey("CheckoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany("CheckoutItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.CustomerPurchaseHistory", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Checkout", "Checkout")
                        .WithMany()
                        .HasForeignKey("CheckoutID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Capstone_RJTech.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.DeliveryDetails", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Delivery", "Delivery")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("delivery_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany("DeliveryDetails")
                        .HasForeignKey("product_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.DeliverySummaryReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Installment", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Checkout", "Checkout")
                        .WithOne("Installment")
                        .HasForeignKey("Capstone_RJTech.Models.Installment", "CheckoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkout");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.InstallmentPayment", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Installment", "Installment")
                        .WithMany("InstallmentPayments")
                        .HasForeignKey("InstallmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installment");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.LeastSellingProductReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.LeastStockedProductReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.MostStockedProductReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Product", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("category_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductCategoryOverviewReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductDeliverySummaryReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductStockSummaryReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.SalesByCategoryReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.TransactionReport", b =>
                {
                    b.HasOne("Capstone_RJTech.Models.Checkout", "Checkout")
                        .WithMany()
                        .HasForeignKey("CheckoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Capstone_RJTech.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Checkout", b =>
                {
                    b.Navigation("CheckoutItems");

                    b.Navigation("Installment");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Customer", b =>
                {
                    b.Navigation("Checkouts");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Delivery", b =>
                {
                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Installment", b =>
                {
                    b.Navigation("InstallmentPayments");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.Product", b =>
                {
                    b.Navigation("CheckoutItems");

                    b.Navigation("DeliveryDetails");
                });

            modelBuilder.Entity("Capstone_RJTech.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
